name: Deploy to Droplet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Debug File Structure
      run: |
        echo "Root Directory:"
        ls -la
        echo "Frontend Directory:"
        ls -la frontend

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang llvm libudev-dev libssl-dev pkg-config

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: wasm32-unknown-unknown

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Download and install Trunk binary
      run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

    - name: Make build.sh executable
      run: chmod +x build.sh

    - name: Build Frontend and Backend
      run: |
        ./build.sh
        cd backend
        cargo build --release

    - name: Deploy Frontend to Droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        source: "dist/*"
        target: "/var/www/your_app/frontend"
        strip_components: 1

    - name: Deploy Backend to Droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        source: "backend/target/release/backend"
        target: "/var/www/your_app/backend"
        strip_components: 3

    - name: Restart Backend Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          sudo systemctl restart your_backend_service
          sudo systemctl status your_backend_service

    - name: Update Nginx Configuration
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          sudo cp /var/www/your_app/nginx.conf /etc/nginx/sites-available/your_app
          sudo ln -sf /etc/nginx/sites-available/your_app /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl reload nginx
