name: Deploy to Droplet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    - name: Install wasm-bindgen-cli
      run: cargo install wasm-bindgen-cli
    - name: Make build script executable
      run: chmod +x ./build.sh
    - name: Build
      run: ./build.sh
    - name: Deploy to Droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        source: "dist/*"
        target: "/var/www/your_app"